version: "3.9"

services:
  backend:
    image: ghcr.io/jerealeksanteri/skilta-piikki-backend:latest
    env_file: .env
    volumes:
      - db-data:/app/data
    environment:
      - DATABASE_URL=sqlite:////app/data/skilta_piikki.db
    restart: unless-stopped
    networks:
      - piikki-net

  frontend:
    image: ghcr.io/jerealeksanteri/skilta-piikki-frontend:latest
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - piikki-net

  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
    env_file: .env
    depends_on:
      - frontend
    restart: unless-stopped
    networks:
      - piikki-net

volumes:
  db-data:
  caddy-data:
  caddy-config:

networks:
  piikki-net:
    driver: bridge
